random_seed: 2021
is_training: 1
model: 'FreTS'
root_path: './datasets/'
data: 'eth'
obs: 8
channel_independence: 1
preds: 12
enc_in: 2
e_layers: 3
n_heads: 4
d_model: 128
d_ff: 256
dropout: 0.1
fc_dropout: 0.1
head_dropout: 0
patch_len: 8
stride: 6
des: 'Exp'
itr: 1
batch_size: 100
learning_rate: 0.00001
lradj: 'TST'
max_epoch: 1000
decomposition: 0
individual: 1
activation: 'gelu'
pct_start: 0.4
